# Generated by Django 4.2.1 on 2023-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('confirmpassword', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(default='', max_length=20)),
                ('applink', models.URLField(default='')),
                ('appcategory', models.CharField(choices=[('entertainment', 'Entertainment'), ('education', 'Education'), ('social networking', 'Social Networking'), ('kids', 'Kids'), ('shopping', 'Shopping'), ('lifestyle', 'Lifestyle')], default='', max_length=20)),
                ('subcategory', models.CharField(choices=[('Gaming', 'Gaming'), ('music Streaming', 'Music Streaming'), ('video Streaming', 'Video Streaming'), ('e-commerce', 'E-Commerce'), ('news', 'News'), ('Messaging', 'Messaging'), ('social media', 'Social Media'), ('communication', 'Communication')], default='', max_length=20)),
                ('points', models.IntegerField(default='')),
            ],
        ),
    ]
