# Generated by Django 4.2.1 on 2023-05-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='subcategory',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('music Streaming', 'Music Streaming'), ('video Streaming', 'Video Streaming'), ('e-commerce', 'E-Commerce'), ('news', 'News'), ('messaging', 'Messaging'), ('social media', 'Social Media'), ('communication', 'Communication')], default='', max_length=20),
        ),
    ]
