# Generated by Django 4.2.1 on 2023-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_apps_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Upload/images/'),
        ),
    ]
