# Generated by Django 4.2.1 on 2023-05-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_apps_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='appcategory',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('education', 'Education'), ('social networking', 'Social Networking'), ('kids', 'Kids'), ('shopping', 'Shopping'), ('design', 'Design'), ('lifestyle', 'Lifestyle')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='apps',
            name='subcategory',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('music Streaming', 'Music Streaming'), ('video Streaming', 'Video Streaming'), ('e-commerce', 'E-Commerce'), ('news', 'News'), ('messaging', 'Messaging'), ('social media', 'Social Media'), ('communication', 'Communication'), ('editing', 'Editing')], default='', max_length=20),
        ),
    ]
