# Generated by Django 4.2.1 on 2023-05-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_alter_apps_appcategory_alter_apps_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Admin.admin'),
        ),
    ]
