# Generated by Django 4.2.1 on 2023-05-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_apps_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.admin'),
        ),
    ]
