# Generated by Django 4.2.1 on 2023-05-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_apps_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apps',
        ),
    ]
