# Generated by Django 4.2.1 on 2023-05-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(default='', max_length=20)),
                ('applink', models.URLField(default='')),
                ('appcategory', models.CharField(choices=[('entertainment', 'Entertainment'), ('education', 'Education'), ('social networking', 'Social Networking'), ('kids', 'Kids'), ('shopping', 'Shopping'), ('design', 'Design'), ('lifestyle', 'Lifestyle')], default='', max_length=20)),
                ('subcategory', models.CharField(choices=[('gaming', 'Gaming'), ('music Streaming', 'Music Streaming'), ('video Streaming', 'Video Streaming'), ('e-commerce', 'E-Commerce'), ('news', 'News'), ('messaging', 'Messaging'), ('social media', 'Social Media'), ('communication', 'Communication'), ('editing', 'Editing')], default='', max_length=20)),
                ('points', models.IntegerField(default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.admin')),
            ],
        ),
    ]
