# Generated by Django 4.2.1 on 2023-05-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_apps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='App',
        ),
    ]
