# Generated by Django 4.2.1 on 2023-05-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_rename_apps_app'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Apps',
        ),
    ]
