# Generated by Django 4.2.1 on 2023-05-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_app_delete_apps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App',
        ),
    ]
