# Generated by Django 4.2.1 on 2023-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(default='', max_length=20)),
                ('points', models.IntegerField(default='')),
                ('screenshot', models.ImageField(null=True, upload_to='screenshot/')),
            ],
        ),
    ]
