# Generated by Django 4.2.1 on 2023-05-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_apps_admin'),
        ('User', '0006_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='appname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.apps'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
