# Generated by Django 4.2.1 on 2023-05-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_task_appname_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='appname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
